# Qualidade da solução

Esse notebook responde sobre a qualidade das soluções obtidas nos experimentos (melhor, média, mediana) comparando as soluções ótimas, heurísticas e meta-heurísticas.

In [1]:
import numpy as np
import pandas as pd
from tabulate import tabulate
from helper import format_number_abnt, unformat_abnt
import matplotlib.pyplot as plt

## Irace - Memetic

Foi executado o irace sob as instâncias menores e maiores separadamente.

### Configuração das instâncias menores 

####  `geneticParameters.txt`:

```
# Parameter 1: max_evaluations
max_evaluations " " i (5, 50)

# Parameter 2: population_size
population_size " " i (10, 200)

# Parameter 3: crossover_rate
crossover_rate " " r (0.1, 0.9)

# Parameter 4: mutation_rate
mutation_rate " " r (0.1, 0.5)
```

#### `irace-config.txt`

```
parameterFile = "./geneticParameters.txt"
trainInstancesDir = "./irace-instances"
maxExperiments = 10000
```

#### Output

```
# Total CPU user time: 91.053, CPU sys time: 6.38, Wall-clock time: 94.421
# Best configurations (first number is the configuration ID; listed from best to worst according to the sum of ranks):
    max_evaluations population_size crossover_rate mutation_rate
15               49             177         0.8031        0.2383
75               21             171         0.3776        0.1478
124              48             184         0.8366        0.2326
95                7             172         0.5386        0.4219
# Best configurations as commandlines (first number is the configuration ID; same order as above):
15    49  177  0.8031  0.2383
75    21  171  0.3776  0.1478
124   48  184  0.8366  0.2326
95    7  172  0.5386  0.4219
```

### Configuração das instâncias maiores

####  `geneticParameters.txt`:

```
# Parameter 1: max_evaluations
max_evaluations " " i (50000, 200000)

# Parameter 2: population_size
population_size " " i (50, 200)

# Parameter 3: crossover_rate
crossover_rate " " r (0.1, 0.9)

# Parameter 4: mutation_rate
mutation_rate " " r (0.1, 0.5)
```

#### `irace-config.txt`

```
parameterFile = "./geneticParameters.txt"
trainInstancesDir = "./irace-big-instances"
maxExperiments = 1000
```

#### Output

```
# Total CPU user time: 509.279, CPU sys time: 8.779, Wall-clock time: 515.332
# Best configurations (first number is the configuration ID; listed from best to worst according to the sum of ranks):
    max_evaluations population_size crossover_rate mutation_rate
117          185974             179         0.6362        0.3448
100          179051             188         0.2209        0.3265
107          184391             183         0.6480        0.3628
49           162271             154         0.1700        0.3115
# Best configurations as commandlines (first number is the configuration ID; same order as above):
117   185974  179  0.6362  0.3448
100   179051  188  0.2209  0.3265
107   184391  183  0.648  0.3628
49    162271  154  0.17  0.3115
```

## Irace - Genetic

### Configuração das instâncias menores 

####  `geneticParameters.txt`:

```
# Parameter 1: max_evaluations
max_evaluations " " i (5, 50)

# Parameter 2: population_size
population_size " " i (10, 200)

# Parameter 3: crossover_rate
crossover_rate " " r (0.1, 0.9)

# Parameter 4: mutation_rate
mutation_rate " " r (0.1, 0.5)
```

#### `irace-config.txt`

```
parameterFile = "./geneticParameters.txt"
trainInstancesDir = "./irace-instances"
maxExperiments = 10000
```

#### Output

```
# Total CPU user time: 102.307, CPU sys time: 6.694, Wall-clock time: 105.86
# Best configurations (first number is the configuration ID; listed from best to worst according to the sum of ranks):
    max_evaluations population_size crossover_rate mutation_rate
92               30             167         0.3170        0.2321
23               35             180         0.2428        0.2005
97               40             179         0.5229        0.2170
112              32             192         0.2176        0.1999
# Best configurations as commandlines (first number is the configuration ID; same order as above):
92    30  167  0.317  0.2321
23    35  180  0.2428  0.2005
97    40  179  0.5229  0.217
112   32  192  0.2176  0.1999
```

### Configuração das instâncias maiores 

####  `geneticParameters.txt`:

```
# Parameter 1: max_evaluations
max_evaluations " " i (50000, 200000)

# Parameter 2: population_size
population_size " " i (50, 200)

# Parameter 3: crossover_rate
crossover_rate " " r (0.1, 0.9)

# Parameter 4: mutation_rate
mutation_rate " " r (0.1, 0.5)
```

#### `irace-config.txt`

```
parameterFile = "./geneticParameters.txt"
trainInstancesDir = "./irace-big-instances"
maxExperiments = 1000
```

#### `Output`

```
# Total CPU user time: 987.744, CPU sys time: 8.223, Wall-clock time: 993.691
# Best configurations (first number is the configuration ID; listed from best to worst according to the sum of ranks):
    max_evaluations population_size crossover_rate mutation_rate
101          171342             160         0.7287        0.3041
102          164036             191         0.4047        0.2048
68           184254             148         0.7329        0.2362
30           179379             180         0.2857        0.2532
# Best configurations as commandlines (first number is the configuration ID; same order as above):
101   171342  160  0.7287  0.3041
102   164036  191  0.4047  0.2048
68    184254  148  0.7329  0.2362
30    179379  180  0.2857  0.2532
```

## Análise preliminar

In [2]:
df_experiments = pd.read_csv('2023-08-20.csv', delimiter=';')

In [3]:
algorithms = df_experiments['algorithm'].unique()
algorithms

array(['Memetic', 'GeneticImproved', 'NearestNeighborhood',
       'CheapestInsertion'], dtype=object)

In [4]:
filenames = df_experiments['filename'].unique()
filenames

array(['data/FIS5-0.txt', 'data/FIS5-1.txt', 'data/FIS5-2.txt',
       'data/FIS5-3.txt', 'data/FIS5-4.txt', 'data/FIS6-0.txt',
       'data/FIS6-1.txt', 'data/FIS6-2.txt', 'data/FIS6-3.txt',
       'data/FIS6-4.txt', 'data/FIS7-0.txt', 'data/FIS7-1.txt',
       'data/FIS7-2.txt', 'data/FIS7-3.txt', 'data/FIS7-4.txt',
       'data/FIS8-0.txt', 'data/FIS8-1.txt', 'data/FIS8-2.txt',
       'data/FIS8-3.txt', 'data/FIS8-4.txt', 'data/FIS9-0.txt',
       'data/FIS9-1.txt', 'data/FIS9-2.txt', 'data/FIS9-3.txt',
       'data/FIS9-4.txt', 'data/FIS10-0.txt', 'data/FIS10-1.txt',
       'data/FIS10-2.txt', 'data/FIS10-3.txt', 'data/FIS10-4.txt',
       'data/FIS11-0.txt', 'data/FIS11-1.txt', 'data/FIS11-2.txt',
       'data/FIS11-3.txt', 'data/FIS11-4.txt', 'data/FIS12-0.txt',
       'data/FIS12-1.txt', 'data/FIS12-2.txt', 'data/FIS12-3.txt',
       'data/FIS12-4.txt', 'data/FIS13-0.txt', 'data/FIS13-1.txt',
       'data/FIS13-2.txt', 'data/FIS13-3.txt', 'data/FIS13-4.txt',
       'data/FIS14-0.txt', 'data/FIS14-1.txt', 'data/FIS14-2.txt',
       'data/FIS14-3.txt', 'data/FIS14-4.txt', 'data/FIS50-0.txt',
       'data/FIS50-1.txt', 'data/FIS50-2.txt', 'data/FIS50-3.txt',
       'data/FIS50-4.txt', 'data/FIS75-0.txt', 'data/FIS75-1.txt',
       'data/FIS75-2.txt', 'data/FIS75-3.txt', 'data/FIS75-4.txt',
       'data/FIS100-0.txt', 'data/FIS100-1.txt', 'data/FIS100-2.txt',
       'data/FIS100-3.txt', 'data/FIS100-4.txt'], dtype=object)

In [5]:
df_result = []

for filename in filenames:
    for algorithm in algorithms:
        df_file_algo = df_experiments[(df_experiments['filename'] == filename) & (df_experiments['algorithm'] == algorithm)]
        desc = df_file_algo.describe()
        result = desc['cost'].to_dict()
        result['milisec'] = desc['milisec']['mean']
        result['filename'] = filename
        result['algorithm'] = algorithm
        df_result.append(result)

df = pd.DataFrame(df_result)
df_result = pd.DataFrame(df_result)

In [6]:
df_result

,count,mean,std,min,25%,50%,75%,max,milisec,filename,algorithm
0,30.0,18430.000000,0.000000,18430.0,18430.00,18430.0,18430.00,18430.0,0.000000,data/FIS5-0.txt,Memetic
1,30.0,18430.000000,0.000000,18430.0,18430.00,18430.0,18430.00,18430.0,0.000000,data/FIS5-0.txt,GeneticImproved
2,30.0,23748.000000,0.000000,23748.0,23748.00,23748.0,23748.00,23748.0,0.000000,data/FIS5-0.txt,NearestNeighborhood
3,30.0,18430.000000,0.000000,18430.0,18430.00,18430.0,18430.00,18430.0,0.000000,data/FIS5-0.txt,CheapestInsertion
4,30.0,22351.000000,0.000000,22351.0,22351.00,22351.0,22351.00,22351.0,0.000000,data/FIS5-1.txt,Memetic
...,...,...,...,...,...,...,...,...,...,...,...
255,30.0,110995.000000,0.000000,110995.0,110995.00,110995.0,110995.00,110995.0,36.233333,data/FIS100-3.txt,CheapestInsertion
256,30.0,69673.666667,4699.946847,60833.0,66252.00,70658.5,73055.75,77334.0,176.600000,data/FIS100-4.txt,Memetic
257,30.0,128267.400000,8872.568884,101983.0,122989.75,129835.0,133223.00,146894.0,412.400000,data/FIS100-4.txt,GeneticImproved
258,30.0,98310.000000,0.000000,98310.0,98310.00,98310.0,98310.00,98310.0,2.000000,data/FIS100-4.txt,NearestNeighborhood
259,30.0,88384.000000,0.000000,88384.0,88384.00,88384.0,88384.00,88384.0,35.766667,data/FIS100-4.txt,CheapestInsertion

In [7]:
df_result['num_before'] = df_result['filename'].str.extract(r'FIS(\d+)-').astype(int)
df_result['num_after'] = df_result['filename'].str.extract(r'-(\d+)').astype(int)

In [8]:
df_result = df_result.sort_values(by=['algorithm', 'num_before', 'num_after']).drop(columns=['num_before', 'num_after'])

In [9]:
df_result = df_result.drop(columns=['count', '25%', '50%', '75%'])

In [10]:
df_result = df_result.round(2)

In [11]:
df_result.head()

,mean,std,min,max,milisec,filename,algorithm
3,18430.0,0.0,18430.0,18430.0,0.0,data/FIS5-0.txt,CheapestInsertion
7,22351.0,0.0,22351.0,22351.0,0.0,data/FIS5-1.txt,CheapestInsertion
11,15356.0,0.0,15356.0,15356.0,0.0,data/FIS5-2.txt,CheapestInsertion
15,21245.0,0.0,21245.0,21245.0,0.0,data/FIS5-3.txt,CheapestInsertion
19,19418.0,0.0,19418.0,19418.0,0.0,data/FIS5-4.txt,CheapestInsertion

In [12]:
algorithms = df_result['algorithm'].unique()

In [13]:
import pandas as pd

# List of algorithms to compare, excluding CheapestInsertion and NearestNeighborhood
algorithms = [alg for alg in df_result['algorithm'].unique() if alg not in ['CheapestInsertion', 'NearestNeighborhood']]

# Prepare data for each algorithm
dataframes = {}
for algorithm in algorithms:
    df_algorithm = df_result[df_result['algorithm'] == algorithm]
    df_algorithm['filename'] = df_algorithm['filename'].str.replace(r'data/FIS(\d+-\d+)\.txt', r'\1', regex=True)
    df_algorithm = df_algorithm[['filename', 'mean', 'std', 'min', 'max', 'milisec']]
    df_algorithm.columns = ['id', f'media_{algorithm}', f'desvio_{algorithm}', f'min_{algorithm}', f'max_{algorithm}', f'tempo_{algorithm}']
    dataframes[algorithm] = df_algorithm

# Merge the dataframes on the 'id' column
combined_df = pd.DataFrame()
for algorithm, df in dataframes.items():
    if combined_df.empty:
        combined_df = df
    else:
        combined_df = pd.merge(combined_df, df, on='id', how='outer')

# Function to unformat numbers (assuming unformat_abnt is defined)
def unformat_cols(val):
    return unformat_abnt(val) if pd.notnull(val) and isinstance(val, str) else val

# Apply unformatting to numeric columns for comparison
numeric_columns = [col for col in combined_df.columns if col != 'id']
combined_df_unformatted = combined_df[numeric_columns].applymap(unformat_cols)

# Start building the LaTeX table
latex_output = "\\begin{tabular}{|" + "c|" * (1 + 5 * len(algorithms)) + "}\n\\hline\n"
header_row = "ID & " + " & ".join(f"Media {alg} & Desvio {alg} & Min {alg} & Max {alg} & Tempo {alg}" for alg in algorithms) + " \\\\\n\\hline\n"
latex_output += header_row

# Function to format a cell with bold if it's the smallest in the group
def format_min_bold(value, min_value):
    return f"\\textbf{{{value}}}" if value == min_value else value

# Iterate over the DataFrame and construct each row
for index, row in combined_df.iterrows():
    row_values = [row['id']]
    for metric in ['media', 'desvio', 'min', 'max', 'tempo']:
        metric_values = [combined_df_unformatted.at[index, f'{metric}_{alg}'] for alg in algorithms if f'{metric}_{alg}' in row]
        min_value = min(metric_values, default=None)
        formatted_values = [combined_df.at[index, f'{metric}_{alg}'] for alg in algorithms if f'{metric}_{alg}' in row]
        row_values.extend([format_min_bold(formatted, min_value) for formatted, unformatted in zip(formatted_values, metric_values)])
    
    latex_output += " & ".join(row_values) + " \\\\\n\\hline\n"

latex_output += "\\end{tabular}"

print(latex_output)

/tmp/ipykernel_32108/490513445.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_algorithm['filename'] = df_algorithm['filename'].str.replace(r'data/FIS(\d+-\d+)\.txt', r'\1', regex=True)
/tmp/ipykernel_32108/490513445.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_algorithm['filename'] = df_algorithm['filename'].str.replace(r'data/FIS(\d+-\d+)\.txt', r'\1', regex=True)
/tmp/ipykernel_32108/490513445.py:29: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  combined_df_unformatted = combined_df[numeric_columns].applymap(unformat_cols)

TypeError: sequence item 2: expected str instance, numpy.float64 found

In [14]:
# List of algorithms to compare, excluding CheapestInsertion and NearestNeighborhood
algorithms = [alg for alg in df_result['algorithm'].unique() if alg not in ['CheapestInsertion', 'NearestNeighborhood']]

# Prepare data for each algorithm
dataframes = {}
for algorithm in algorithms:
    df_algorithm = df_result[df_result['algorithm'] == algorithm]
    df_algorithm['filename'] = df_algorithm['filename'].str.replace(r'data/FIS(\d+-\d+)\.txt', r'\1', regex=True)
    df_algorithm = df_algorithm[['filename', 'mean', 'std', 'min', 'max', 'milisec']]
    df_algorithm.columns = ['id', f'media_{algorithm}', f'desvio_{algorithm}', f'min_{algorithm}', f'max_{algorithm}', f'tempo_{algorithm}']
    dataframes[algorithm] = df_algorithm

# Function to format numbers (assuming format_number_abnt is defined)
def format_cols(val):
    return format_number_abnt(val)

# Merge the dataframes on the 'id' column
combined_df = pd.DataFrame()
for algorithm, df in dataframes.items():
    if combined_df.empty:
        combined_df = df
    else:
        combined_df = pd.merge(combined_df, df, on='id', how='outer')

# Apply formatting
numeric_columns = [col for col in combined_df.columns if col != 'id']
combined_df[numeric_columns] = combined_df[numeric_columns].applymap(format_cols)

# Start building the LaTeX table
latex_output = "\\begin{tabular}{|" + "c|" * (1 + 5 * len(algorithms)) + "}\n\\hline\n"
header_row = "ID & " + " & ".join(f"Media {alg} & Desvio {alg} & Min {alg} & Max {alg} & Tempo {alg}" for alg in algorithms) + " \\\\\n\\hline\n"
latex_output += header_row

# Function to format a cell with bold if it's the smallest in the group
def format_min_bold(value, min_value):
    return f"\\textbf{{{value}}}" if value == min_value else value

# Iterate over the DataFrame and construct each row
for index, row in combined_df.iterrows():
    row_values = [row['id']]
    for metric in ['media', 'desvio', 'min', 'max', 'tempo']:
        metric_values = [row[f'{metric}_{alg}'] for alg in algorithms if f'{metric}_{alg}' in row]
        min_value = min(metric_values, default=None)
        row_values.extend([format_min_bold(value, min_value) for value in metric_values])
    
    latex_output += " & ".join(row_values) + " \\\\\n\\hline\n"

latex_output += "\\end{tabular}"

print(latex_output)

\begin{tabular}{|c|c|c|c|c|c|c|c|c|c|c|}
\hline
ID & Media GeneticImproved & Desvio GeneticImproved & Min GeneticImproved & Max GeneticImproved & Tempo GeneticImproved & Media Memetic & Desvio Memetic & Min Memetic & Max Memetic & Tempo Memetic \\
\hline
5-0 & \textbf{18.430,00} & \textbf{18.430,00} & \textbf{0,00} & \textbf{0,00} & \textbf{18.430,00} & \textbf{18.430,00} & \textbf{18.430,00} & \textbf{18.430,00} & \textbf{0,00} & \textbf{0,00} \\
\hline
5-1 & \textbf{22.351,00} & \textbf{22.351,00} & \textbf{0,00} & \textbf{0,00} & \textbf{22.351,00} & \textbf{22.351,00} & \textbf{22.351,00} & \textbf{22.351,00} & \textbf{0,00} & \textbf{0,00} \\
\hline
5-2 & \textbf{15.356,00} & \textbf{15.356,00} & \textbf{0,00} & \textbf{0,00} & \textbf{15.356,00} & \textbf{15.356,00} & \textbf{15.356,00} & \textbf{15.356,00} & \textbf{0,00} & \textbf{0,00} \\
\hline
5-3 & \textbf{21.245,00} & \textbf{21.245,00} & \textbf{0,00} & \textbf{0,00} & \textbf{21.245,00} & \textbf{21.245,00} & \textbf{21.245,00} & \textbf{21.245,00} & \textbf{0,00} & \textbf{0,00} \\
\hline
5-4 & \textbf{19.418,00} & \textbf{19.418,00} & \textbf{0,00} & \textbf{0,00} & \textbf{19.418,00} & \textbf{19.418,00} & \textbf{19.418,00} & \textbf{19.418,00} & \textbf{0,00} & \textbf{0,00} \\
\hline
6-0 & \textbf{15.576,00} & \textbf{15.576,00} & \textbf{0,00} & \textbf{0,00} & \textbf{15.576,00} & \textbf{15.576,00} & \textbf{15.576,00} & \textbf{15.576,00} & \textbf{0,00} & \textbf{0,00} \\
\hline
6-1 & \textbf{19.720,93} & \textbf{19.720,93} & \textbf{738,86} & \textbf{738,86} & \textbf{19.436,00} & \textbf{19.436,00} & \textbf{21.573,00} & \textbf{21.573,00} & \textbf{0,00} & \textbf{0,00} \\
\hline
6-2 & \textbf{23.991,00} & \textbf{23.991,00} & \textbf{0,00} & \textbf{0,00} & \textbf{23.991,00} & \textbf{23.991,00} & \textbf{23.991,00} & \textbf{23.991,00} & \textbf{0,00} & \textbf{0,00} \\
\hline
6-3 & \textbf{14.055,80} & \textbf{14.055,80} & \textbf{614,04} & \textbf{614,04} & \textbf{13.819,00} & \textbf{13.819,00} & \textbf{15.595,00} & \textbf{15.595,00} & \textbf{0,00} & \textbf{0,00} \\
\hline
6-4 & \textbf{16.139,00} & 16.407,10 & \textbf{0,00} & 818,05 & \textbf{16.139,00} & \textbf{16.139,00} & \textbf{16.139,00} & 18.820,00 & \textbf{0,00} & \textbf{0,00} \\
\hline
7-0 & 17.150,80 & \textbf{16.628,13} & 987,00 & \textbf{402,09} & \textbf{16.355,00} & \textbf{16.355,00} & 19.927,00 & \textbf{17.777,00} & \textbf{0,00} & \textbf{0,00} \\
\hline
7-1 & 21.606,13 & \textbf{21.577,73} & 1.404,45 & \textbf{1.394,83} & \textbf{20.251,00} & \textbf{20.251,00} & 25.079,00 & \textbf{24.907,00} & \textbf{0,00} & \textbf{0,00} \\
\hline
7-2 & 9.900,67 & \textbf{9.523,57} & \textbf{1.247,38} & 1.300,01 & \textbf{8.243,00} & \textbf{8.243,00} & \textbf{11.280,00} & \textbf{11.280,00} & \textbf{0,00} & \textbf{0,00} \\
\hline
7-3 & 20.496,77 & \textbf{20.311,60} & 1.264,60 & \textbf{1.122,45} & \textbf{19.494,00} & \textbf{19.494,00} & 22.933,00 & \textbf{22.561,00} & \textbf{0,00} & \textbf{0,00} \\
\hline
7-4 & \textbf{24.395,00} & \textbf{24.395,00} & \textbf{0,00} & \textbf{0,00} & \textbf{24.395,00} & \textbf{24.395,00} & \textbf{24.395,00} & \textbf{24.395,00} & \textbf{0,00} & \textbf{0,00} \\
\hline
8-0 & \textbf{22.343,30} & 22.529,93 & \textbf{1.554,71} & 1.790,81 & \textbf{20.047,00} & \textbf{20.047,00} & \textbf{26.071,00} & 26.082,00 & \textbf{0,00} & \textbf{0,00} \\
\hline
8-1 & 22.280,43 & \textbf{21.553,83} & \textbf{1.641,28} & 1.773,16 & 18.639,00 & \textbf{17.845,00} & \textbf{24.758,00} & 25.535,00 & \textbf{0,00} & \textbf{0,00} \\
\hline
8-2 & \textbf{22.089,60} & 22.807,67 & 3.796,75 & \textbf{2.558,31} & \textbf{12.652,00} & 17.726,00 & \textbf{27.044,00} & 27.232,00 & \textbf{0,00} & \textbf{0,00} \\
\hline
8-3 & \textbf{19.931,23} & 20.180,80 & 2.866,32 & \textbf{2.038,94} & \textbf{15.018,00} & \textbf{15.018,00} & 23.950,00 & \textbf{22.918,00} & \textbf{0,00} & \textbf{0,00} \\
\hline
8-4 & \textbf{21.571,13} & 21.605,73 & 1.151,41 & \textbf{1.103,07} & \textbf{19.030,00} & 20.010,00 & 25.246,00 & \textbf{23.588,00} & \textbf{0,00} & \textbf{0,00} \\
\hline
9-0 & \textbf{26.292,83} & 26.318,80 & 2.178,05 & \textbf{1.876,86} & \textbf{21.699,00} & \textbf{21.699,00} & \textbf{28.358,00} & \textbf{28.358,00} & \textbf{0,00} & \textbf{0,00} \\
\hline
9-1 & \textbf{29.864,83} & 30.335,43 & 1.958,95 & \textbf{1.470,69} & \textbf{26.092,00} & 27.468,00 & 33.519,00 & \textbf{33.323,00} & \textbf{0,00} & \textbf{0,00} \\
\hline
9-2 & 33.671,17 & \textbf{33.637,70} & \textbf{1.379,19} & 1.542,32 & 30.846,00 & \textbf{29.485,00} & \textbf{34.913,00} & \textbf{34.913,00} & \textbf{0,00} & \textbf{0,00} \\
\hline
9-3 & \textbf{22.403,37} & 22.473,47 & 823,88 & \textbf{618,12} & \textbf{19.736,00} & 20.746,00 & \textbf{22.739,00} & \textbf{22.739,00} & \textbf{0,00} & \textbf{0,00} \\
\hline
9-4 & \textbf{25.693,20} & 26.527,33 & 2.494,81 & \textbf{2.094,12} & \textbf{21.566,00} & 22.879,00 & 30.968,00 & \textbf{30.243,00} & \textbf{0,00} & \textbf{0,00} \\
\hline
10-0 & 31.114,23 & \textbf{31.100,47} & \textbf{2.346,68} & 2.900,61 & 26.641,00 & \textbf{24.017,00} & 36.000,00 & \textbf{34.573,00} & \textbf{0,00} & \textbf{0,00} \\
\hline
10-1 & 32.221,13 & \textbf{32.191,17} & 2.849,08 & \textbf{2.474,94} & \textbf{25.398,00} & 26.975,00 & \textbf{36.418,00} & 37.247,00 & \textbf{0,00} & \textbf{0,00} \\
\hline
10-2 & 32.951,43 & \textbf{32.863,47} & \textbf{2.313,04} & 2.543,45 & 28.688,00 & \textbf{28.176,00} & \textbf{36.736,00} & 37.504,00 & \textbf{0,00} & \textbf{0,00} \\
\hline
10-3 & \textbf{30.036,13} & 30.830,77 & 2.509,35 & \textbf{2.205,76} & \textbf{23.018,00} & 27.498,00 & \textbf{35.209,00} & 35.485,00 & \textbf{0,00} & \textbf{0,00} \\
\hline
10-4 & 23.387,40 & \textbf{22.564,23} & \textbf{2.099,31} & 2.223,72 & 19.506,00 & \textbf{17.690,00} & 27.526,00 & \textbf{26.262,00} & \textbf{0,00} & \textbf{0,00} \\
\hline
11-0 & 35.914,73 & \textbf{35.306,13} & \textbf{3.139,44} & 3.385,20 & 29.236,00 & \textbf{26.894,00} & 41.725,00 & \textbf{40.333,00} & \textbf{0,00} & \textbf{0,00} \\
\hline
11-1 & 38.758,73 & \textbf{38.019,90} & 2.585,80 & \textbf{2.509,85} & 34.691,00 & \textbf{34.178,00} & 44.407,00 & \textbf{43.026,00} & \textbf{0,00} & \textbf{0,00} \\
\hline
11-2 & \textbf{34.885,60} & 34.967,47 & 3.167,45 & \textbf{1.917,75} & \textbf{26.836,00} & 31.565,00 & 39.683,00 & \textbf{37.850,00} & \textbf{0,00} & \textbf{0,00} \\
\hline
11-3 & 35.725,27 & \textbf{34.830,10} & 2.669,39 & \textbf{2.425,46} & \textbf{29.941,00} & 30.687,00 & \textbf{40.028,00} & \textbf{40.028,00} & \textbf{0,00} & \textbf{0,00} \\
\hline
11-4 & 34.019,37 & \textbf{33.775,77} & 3.219,85 & \textbf{3.067,50} & \textbf{24.233,00} & 26.463,00 & \textbf{39.241,00} & \textbf{39.241,00} & \textbf{0,00} & \textbf{0,00} \\
\hline
12-0 & 41.956,27 & \textbf{41.764,27} & 3.230,46 & \textbf{2.465,60} & \textbf{31.457,00} & 35.013,00 & \textbf{45.017,00} & \textbf{45.017,00} & \textbf{0,00} & \textbf{0,00} \\
\hline
12-1 & 40.653,80 & \textbf{40.340,53} & 3.089,28 & \textbf{2.413,79} & \textbf{32.741,00} & 35.779,00 & \textbf{43.148,00} & \textbf{43.148,00} & \textbf{0,00} & \textbf{0,00} \\
\hline
12-2 & 45.833,27 & \textbf{45.308,63} & \textbf{3.141,70} & 3.581,72 & 40.377,00 & \textbf{36.524,00} & 53.577,00 & \textbf{50.917,00} & \textbf{0,00} & \textbf{0,00} \\
\hline
12-3 & 36.214,67 & \textbf{35.370,47} & 3.260,35 & \textbf{2.707,82} & 28.810,00 & \textbf{27.219,00} & 42.040,00 & \textbf{41.549,00} & \textbf{0,00} & \textbf{0,00} \\
\hline
12-4 & 35.652,90 & \textbf{35.355,00} & 121,05 & \textbf{1.564,35} & 35.012,00 & \textbf{27.136,00} & \textbf{35.675,00} & \textbf{35.675,00} & \textbf{0,00} & \textbf{0,00} \\
\hline
13-0 & 44.840,50 & \textbf{44.245,43} & \textbf{3.722,80} & 5.140,58 & 36.087,00 & \textbf{26.259,00} & \textbf{50.523,00} & \textbf{50.523,00} & \textbf{0,00} & \textbf{0,00} \\
\hline
13-1 & 47.311,90 & \textbf{47.192,13} & \textbf{3.453,42} & 3.612,88 & 39.625,00 & \textbf{37.139,00} & 53.683,00 & \textbf{52.075,00} & \textbf{0,00} & \textbf{0,00} \\
\hline
13-2 & 47.041,33 & \textbf{46.707,33} & 3.091,89 & \textbf{2.876,07} & \textbf{37.462,00} & 39.626,00 & \textbf{49.787,00} & \textbf{49.787,00} & \textbf{0,00} & \textbf{0,00} \\
\hline
13-3 & 40.595,93 & \textbf{38.236,10} & \textbf{3.779,58} & 4.055,00 & 30.653,00 & \textbf{30.162,00} & 46.704,00 & \textbf{44.824,00} & \textbf{0,00} & \textbf{0,00} \\
\hline
13-4 & \textbf{40.211,33} & 40.994,70 & 3.691,80 & \textbf{2.805,36} & \textbf{30.544,00} & 31.133,00 & \textbf{43.931,00} & \textbf{43.931,00} & \textbf{0,00} & \textbf{0,00} \\
\hline
14-0 & \textbf{45.978,50} & 46.202,13 & \textbf{3.554,42} & 3.568,23 & 38.071,00 & \textbf{36.932,00} & \textbf{52.940,00} & 53.050,00 & \textbf{0,00} & \textbf{0,00} \\
\hline
14-1 & 53.192,47 & \textbf{52.311,13} & \textbf{3.132,22} & 3.804,77 & 44.905,00 & \textbf{43.816,00} & \textbf{57.918,00} & 58.442,00 & \textbf{0,00} & \textbf{0,00} \\
\hline
14-2 & 49.055,00 & \textbf{48.081,83} & 3.721,61 & \textbf{3.120,08} & 41.976,00 & \textbf{41.310,00} & 54.541,00 & \textbf{53.250,00} & \textbf{0,00} & \textbf{0,00} \\
\hline
14-3 & 48.839,07 & \textbf{48.039,63} & \textbf{2.918,64} & 3.308,78 & 44.045,00 & \textbf{41.717,00} & \textbf{54.227,00} & 54.314,00 & \textbf{0,00} & \textbf{0,00} \\
\hline
14-4 & 51.061,63 & \textbf{50.202,67} & \textbf{3.652,06} & 3.816,22 & \textbf{40.409,00} & 43.666,00 & 57.734,00 & \textbf{57.162,00} & \textbf{0,00} & \textbf{0,00} \\
\hline
50-0 & 61.523,90 & \textbf{42.049,90} & 6.711,40 & \textbf{1.691,20} & 52.905,00 & \textbf{38.028,00} & 79.422,00 & \textbf{45.199,00} & \textbf{223,53} & 38,27 \\
\hline
50-1 & 63.213,00 & \textbf{43.746,23} & 5.465,67 & \textbf{2.057,01} & 49.951,00 & \textbf{38.932,00} & 77.566,00 & \textbf{48.072,00} & \textbf{225,87} & 38,20 \\
\hline
50-2 & 64.692,47 & \textbf{43.919,40} & 5.189,93 & \textbf{1.702,71} & 56.604,00 & \textbf{41.173,00} & 78.037,00 & \textbf{47.435,00} & \textbf{224,50} & 38,03 \\
\hline
50-3 & 58.144,77 & \textbf{40.531,03} & 5.188,43 & \textbf{1.744,95} & 45.609,00 & \textbf{37.277,00} & 69.919,00 & \textbf{43.485,00} & \textbf{224,87} & 38,27 \\
\hline
50-4 & 65.042,13 & \textbf{47.337,60} & 5.341,32 & \textbf{1.875,34} & 55.076,00 & \textbf{43.827,00} & 78.688,00 & \textbf{52.075,00} & \textbf{225,77} & 38,53 \\
\hline
75-0 & 95.186,80 & \textbf{60.065,43} & 7.573,00 & \textbf{1.449,45} & 81.653,00 & \textbf{54.674,00} & \textbf{118.561,00} & 63.188,00 & \textbf{312,83} & 85,70 \\
\hline
75-1 & 91.305,77 & \textbf{57.551,73} & 7.369,88 & \textbf{1.980,91} & 75.680,00 & \textbf{53.679,00} & \textbf{104.629,00} & 62.371,00 & \textbf{311,63} & 85,50 \\
\hline
75-2 & 96.433,67 & \textbf{58.906,93} & 6.155,89 & \textbf{3.169,14} & 82.820,00 & \textbf{49.989,00} & \textbf{109.908,00} & 64.021,00 & \textbf{312,37} & 86,00 \\
\hline
75-3 & 92.104,37 & \textbf{54.406,27} & 8.512,54 & \textbf{3.655,44} & 78.280,00 & \textbf{47.796,00} & \textbf{109.581,00} & 61.561,00 & \textbf{312,60} & 85,07 \\
\hline
75-4 & 95.796,57 & \textbf{59.340,47} & 6.462,50 & \textbf{2.759,21} & 79.952,00 & \textbf{54.673,00} & \textbf{109.544,00} & 66.076,00 & \textbf{311,90} & 85,70 \\
\hline
100-0 & \textbf{123.195,40} & 71.885,23 & \textbf{10.459,29} & 3.790,07 & \textbf{104.240,00} & 69.333,00 & \textbf{141.843,00} & 80.772,00 & 406,93 & \textbf{176,80} \\
\hline
100-1 & \textbf{130.871,50} & 76.400,67 & 8.406,53 & \textbf{3.018,39} & \textbf{117.475,00} & 71.913,00 & \textbf{149.618,00} & 85.389,00 & 413,47 & \textbf{175,13} \\
\hline
100-2 & \textbf{128.835,50} & 72.033,00 & 8.604,97 & \textbf{3.260,31} & \textbf{114.894,00} & 66.123,00 & \textbf{148.618,00} & 77.136,00 & 414,30 & \textbf{176,40} \\
\hline
100-3 & \textbf{132.947,30} & 73.613,17 & 7.705,20 & \textbf{2.168,03} & \textbf{119.049,00} & 68.195,00 & \textbf{151.987,00} & 80.522,00 & 411,83 & \textbf{176,57} \\
\hline
100-4 & \textbf{128.267,40} & 69.673,67 & 8.872,57 & \textbf{4.699,95} & \textbf{101.983,00} & 60.833,00 & \textbf{146.894,00} & 77.334,00 & 412,40 & \textbf{176,60} \\
\hline
\end{tabular}

/tmp/ipykernel_32108/2897880675.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_algorithm['filename'] = df_algorithm['filename'].str.replace(r'data/FIS(\d+-\d+)\.txt', r'\1', regex=True)
/tmp/ipykernel_32108/2897880675.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_algorithm['filename'] = df_algorithm['filename'].str.replace(r'data/FIS(\d+-\d+)\.txt', r'\1', regex=True)
/tmp/ipykernel_32108/2897880675.py:27: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  combined_df[numeric_columns] = combined_df[numeric_columns].applymap(format_cols)

In [15]:
# List of algorithms to compare, excluding CheapestInsertion and NearestNeighborhood
algorithms = [alg for alg in df_result['algorithm'].unique() if alg not in ['CheapestInsertion', 'NearestNeighborhood']]

# Prepare data for each algorithm
dataframes = {}
for algorithm in algorithms:
    df_algorithm = df_result[df_result['algorithm'] == algorithm]
    df_algorithm['filename'] = df_algorithm['filename'].str.replace(r'data/FIS(\d+-\d+)\.txt', r'\1', regex=True)
    df_algorithm = df_algorithm[['filename', 'mean', 'std', 'min', 'max', 'milisec']]
    df_algorithm.columns = ['id', f'media_{algorithm}', f'desvio_{algorithm}', f'min_{algorithm}', f'max_{algorithm}', f'tempo_{algorithm}']
    dataframes[algorithm] = df_algorithm

# Merge the dataframes on the 'id' column
combined_df = pd.DataFrame()
for algorithm, df in dataframes.items():
    if combined_df.empty:
        combined_df = df
    else:
        combined_df = pd.merge(combined_df, df, on='id', how='outer')

# Convert formatted strings to numbers for comparison
for col in combined_df.columns:
    if col != 'id' and 'filename' not in col:
        combined_df[col] = combined_df[col].apply(unformat_abnt)

# Function to format a cell with bold if it's the smallest in the group
def format_min_bold(value, min_value):
    return f"\\textbf{{{format_cols(value)}}}" if value == min_value else format_cols(value)

# Start building the LaTeX table
latex_output = "\\begin{tabular}{|" + "c|" * (1 + 5 * len(algorithms)) + "}\n\\hline\n"
header_row = "ID & " + " & ".join(f"Media {alg} & Desvio {alg} & Min {alg} & Max {alg} & Tempo {alg}" for alg in algorithms) + " \\\\\n\\hline\n"
latex_output += header_row

# Iterate over the DataFrame and construct each row
for index, row in combined_df.iterrows():
    row_values = [row['id']]
    for metric in ['media', 'desvio', 'min', 'max', 'tempo']:
        metric_values = [row[f'{metric}_{alg}'] for alg in algorithms if f'{metric}_{alg}' in row]
        min_value = min(metric_values, default=None)
        row_values.extend([format_min_bold(value, min_value) for value in metric_values])
    
    latex_output += " & ".join(str(val) for val in row_values) + " \\\\\n\\hline\n"

latex_output += "\\end{tabular}"

print(latex_output)

\begin{tabular}{|c|c|c|c|c|c|c|c|c|c|c|}
\hline
ID & Media GeneticImproved & Desvio GeneticImproved & Min GeneticImproved & Max GeneticImproved & Tempo GeneticImproved & Media Memetic & Desvio Memetic & Min Memetic & Max Memetic & Tempo Memetic \\
\hline
5-0 & \textbf{18.430,00} & \textbf{18.430,00} & \textbf{0,00} & \textbf{0,00} & \textbf{18.430,00} & \textbf{18.430,00} & \textbf{18.430,00} & \textbf{18.430,00} & \textbf{0,00} & \textbf{0,00} \\
\hline
5-1 & \textbf{22.351,00} & \textbf{22.351,00} & \textbf{0,00} & \textbf{0,00} & \textbf{22.351,00} & \textbf{22.351,00} & \textbf{22.351,00} & \textbf{22.351,00} & \textbf{0,00} & \textbf{0,00} \\
\hline
5-2 & \textbf{15.356,00} & \textbf{15.356,00} & \textbf{0,00} & \textbf{0,00} & \textbf{15.356,00} & \textbf{15.356,00} & \textbf{15.356,00} & \textbf{15.356,00} & \textbf{0,00} & \textbf{0,00} \\
\hline
5-3 & \textbf{21.245,00} & \textbf{21.245,00} & \textbf{0,00} & \textbf{0,00} & \textbf{21.245,00} & \textbf{21.245,00} & \textbf{21.245,00} & \textbf{21.245,00} & \textbf{0,00} & \textbf{0,00} \\
\hline
5-4 & \textbf{19.418,00} & \textbf{19.418,00} & \textbf{0,00} & \textbf{0,00} & \textbf{19.418,00} & \textbf{19.418,00} & \textbf{19.418,00} & \textbf{19.418,00} & \textbf{0,00} & \textbf{0,00} \\
\hline
6-0 & \textbf{15.576,00} & \textbf{15.576,00} & \textbf{0,00} & \textbf{0,00} & \textbf{15.576,00} & \textbf{15.576,00} & \textbf{15.576,00} & \textbf{15.576,00} & \textbf{0,00} & \textbf{0,00} \\
\hline
6-1 & \textbf{19.720,93} & \textbf{19.720,93} & \textbf{738,86} & \textbf{738,86} & \textbf{19.436,00} & \textbf{19.436,00} & \textbf{21.573,00} & \textbf{21.573,00} & \textbf{0,00} & \textbf{0,00} \\
\hline
6-2 & \textbf{23.991,00} & \textbf{23.991,00} & \textbf{0,00} & \textbf{0,00} & \textbf{23.991,00} & \textbf{23.991,00} & \textbf{23.991,00} & \textbf{23.991,00} & \textbf{0,00} & \textbf{0,00} \\
\hline
6-3 & \textbf{14.055,80} & \textbf{14.055,80} & \textbf{614,04} & \textbf{614,04} & \textbf{13.819,00} & \textbf{13.819,00} & \textbf{15.595,00} & \textbf{15.595,00} & \textbf{0,00} & \textbf{0,00} \\
\hline
6-4 & \textbf{16.139,00} & 16.407,10 & \textbf{0,00} & 818,05 & \textbf{16.139,00} & \textbf{16.139,00} & \textbf{16.139,00} & 18.820,00 & \textbf{0,00} & \textbf{0,00} \\
\hline
7-0 & 17.150,80 & \textbf{16.628,13} & 987,00 & \textbf{402,09} & \textbf{16.355,00} & \textbf{16.355,00} & 19.927,00 & \textbf{17.777,00} & \textbf{0,00} & \textbf{0,00} \\
\hline
7-1 & 21.606,13 & \textbf{21.577,73} & 1.404,45 & \textbf{1.394,83} & \textbf{20.251,00} & \textbf{20.251,00} & 25.079,00 & \textbf{24.907,00} & \textbf{0,00} & \textbf{0,00} \\
\hline
7-2 & 9.900,67 & \textbf{9.523,57} & \textbf{1.247,38} & 1.300,01 & \textbf{8.243,00} & \textbf{8.243,00} & \textbf{11.280,00} & \textbf{11.280,00} & \textbf{0,00} & \textbf{0,00} \\
\hline
7-3 & 20.496,77 & \textbf{20.311,60} & 1.264,60 & \textbf{1.122,45} & \textbf{19.494,00} & \textbf{19.494,00} & 22.933,00 & \textbf{22.561,00} & \textbf{0,00} & \textbf{0,00} \\
\hline
7-4 & \textbf{24.395,00} & \textbf{24.395,00} & \textbf{0,00} & \textbf{0,00} & \textbf{24.395,00} & \textbf{24.395,00} & \textbf{24.395,00} & \textbf{24.395,00} & \textbf{0,00} & \textbf{0,00} \\
\hline
8-0 & \textbf{22.343,30} & 22.529,93 & \textbf{1.554,71} & 1.790,81 & \textbf{20.047,00} & \textbf{20.047,00} & \textbf{26.071,00} & 26.082,00 & \textbf{0,00} & \textbf{0,00} \\
\hline
8-1 & 22.280,43 & \textbf{21.553,83} & \textbf{1.641,28} & 1.773,16 & 18.639,00 & \textbf{17.845,00} & \textbf{24.758,00} & 25.535,00 & \textbf{0,00} & \textbf{0,00} \\
\hline
8-2 & \textbf{22.089,60} & 22.807,67 & 3.796,75 & \textbf{2.558,31} & \textbf{12.652,00} & 17.726,00 & \textbf{27.044,00} & 27.232,00 & \textbf{0,00} & \textbf{0,00} \\
\hline
8-3 & \textbf{19.931,23} & 20.180,80 & 2.866,32 & \textbf{2.038,94} & \textbf{15.018,00} & \textbf{15.018,00} & 23.950,00 & \textbf{22.918,00} & \textbf{0,00} & \textbf{0,00} \\
\hline
8-4 & \textbf{21.571,13} & 21.605,73 & 1.151,41 & \textbf{1.103,07} & \textbf{19.030,00} & 20.010,00 & 25.246,00 & \textbf{23.588,00} & \textbf{0,00} & \textbf{0,00} \\
\hline
9-0 & \textbf{26.292,83} & 26.318,80 & 2.178,05 & \textbf{1.876,86} & \textbf{21.699,00} & \textbf{21.699,00} & \textbf{28.358,00} & \textbf{28.358,00} & \textbf{0,00} & \textbf{0,00} \\
\hline
9-1 & \textbf{29.864,83} & 30.335,43 & 1.958,95 & \textbf{1.470,69} & \textbf{26.092,00} & 27.468,00 & 33.519,00 & \textbf{33.323,00} & \textbf{0,00} & \textbf{0,00} \\
\hline
9-2 & 33.671,17 & \textbf{33.637,70} & \textbf{1.379,19} & 1.542,32 & 30.846,00 & \textbf{29.485,00} & \textbf{34.913,00} & \textbf{34.913,00} & \textbf{0,00} & \textbf{0,00} \\
\hline
9-3 & \textbf{22.403,37} & 22.473,47 & 823,88 & \textbf{618,12} & \textbf{19.736,00} & 20.746,00 & \textbf{22.739,00} & \textbf{22.739,00} & \textbf{0,00} & \textbf{0,00} \\
\hline
9-4 & \textbf{25.693,20} & 26.527,33 & 2.494,81 & \textbf{2.094,12} & \textbf{21.566,00} & 22.879,00 & 30.968,00 & \textbf{30.243,00} & \textbf{0,00} & \textbf{0,00} \\
\hline
10-0 & 31.114,23 & \textbf{31.100,47} & \textbf{2.346,68} & 2.900,61 & 26.641,00 & \textbf{24.017,00} & 36.000,00 & \textbf{34.573,00} & \textbf{0,00} & \textbf{0,00} \\
\hline
10-1 & 32.221,13 & \textbf{32.191,17} & 2.849,08 & \textbf{2.474,94} & \textbf{25.398,00} & 26.975,00 & \textbf{36.418,00} & 37.247,00 & \textbf{0,00} & \textbf{0,00} \\
\hline
10-2 & 32.951,43 & \textbf{32.863,47} & \textbf{2.313,04} & 2.543,45 & 28.688,00 & \textbf{28.176,00} & \textbf{36.736,00} & 37.504,00 & \textbf{0,00} & \textbf{0,00} \\
\hline
10-3 & \textbf{30.036,13} & 30.830,77 & 2.509,35 & \textbf{2.205,76} & \textbf{23.018,00} & 27.498,00 & \textbf{35.209,00} & 35.485,00 & \textbf{0,00} & \textbf{0,00} \\
\hline
10-4 & 23.387,40 & \textbf{22.564,23} & \textbf{2.099,31} & 2.223,72 & 19.506,00 & \textbf{17.690,00} & 27.526,00 & \textbf{26.262,00} & \textbf{0,00} & \textbf{0,00} \\
\hline
11-0 & 35.914,73 & \textbf{35.306,13} & \textbf{3.139,44} & 3.385,20 & 29.236,00 & \textbf{26.894,00} & 41.725,00 & \textbf{40.333,00} & \textbf{0,00} & \textbf{0,00} \\
\hline
11-1 & 38.758,73 & \textbf{38.019,90} & 2.585,80 & \textbf{2.509,85} & 34.691,00 & \textbf{34.178,00} & 44.407,00 & \textbf{43.026,00} & \textbf{0,00} & \textbf{0,00} \\
\hline
11-2 & \textbf{34.885,60} & 34.967,47 & 3.167,45 & \textbf{1.917,75} & \textbf{26.836,00} & 31.565,00 & 39.683,00 & \textbf{37.850,00} & \textbf{0,00} & \textbf{0,00} \\
\hline
11-3 & 35.725,27 & \textbf{34.830,10} & 2.669,39 & \textbf{2.425,46} & \textbf{29.941,00} & 30.687,00 & \textbf{40.028,00} & \textbf{40.028,00} & \textbf{0,00} & \textbf{0,00} \\
\hline
11-4 & 34.019,37 & \textbf{33.775,77} & 3.219,85 & \textbf{3.067,50} & \textbf{24.233,00} & 26.463,00 & \textbf{39.241,00} & \textbf{39.241,00} & \textbf{0,00} & \textbf{0,00} \\
\hline
12-0 & 41.956,27 & \textbf{41.764,27} & 3.230,46 & \textbf{2.465,60} & \textbf{31.457,00} & 35.013,00 & \textbf{45.017,00} & \textbf{45.017,00} & \textbf{0,00} & \textbf{0,00} \\
\hline
12-1 & 40.653,80 & \textbf{40.340,53} & 3.089,28 & \textbf{2.413,79} & \textbf{32.741,00} & 35.779,00 & \textbf{43.148,00} & \textbf{43.148,00} & \textbf{0,00} & \textbf{0,00} \\
\hline
12-2 & 45.833,27 & \textbf{45.308,63} & \textbf{3.141,70} & 3.581,72 & 40.377,00 & \textbf{36.524,00} & 53.577,00 & \textbf{50.917,00} & \textbf{0,00} & \textbf{0,00} \\
\hline
12-3 & 36.214,67 & \textbf{35.370,47} & 3.260,35 & \textbf{2.707,82} & 28.810,00 & \textbf{27.219,00} & 42.040,00 & \textbf{41.549,00} & \textbf{0,00} & \textbf{0,00} \\
\hline
12-4 & 35.652,90 & \textbf{35.355,00} & \textbf{121,05} & 1.564,35 & 35.012,00 & \textbf{27.136,00} & \textbf{35.675,00} & \textbf{35.675,00} & \textbf{0,00} & \textbf{0,00} \\
\hline
13-0 & 44.840,50 & \textbf{44.245,43} & \textbf{3.722,80} & 5.140,58 & 36.087,00 & \textbf{26.259,00} & \textbf{50.523,00} & \textbf{50.523,00} & \textbf{0,00} & \textbf{0,00} \\
\hline
13-1 & 47.311,90 & \textbf{47.192,13} & \textbf{3.453,42} & 3.612,88 & 39.625,00 & \textbf{37.139,00} & 53.683,00 & \textbf{52.075,00} & \textbf{0,00} & \textbf{0,00} \\
\hline
13-2 & 47.041,33 & \textbf{46.707,33} & 3.091,89 & \textbf{2.876,07} & \textbf{37.462,00} & 39.626,00 & \textbf{49.787,00} & \textbf{49.787,00} & \textbf{0,00} & \textbf{0,00} \\
\hline
13-3 & 40.595,93 & \textbf{38.236,10} & \textbf{3.779,58} & 4.055,00 & 30.653,00 & \textbf{30.162,00} & 46.704,00 & \textbf{44.824,00} & \textbf{0,00} & \textbf{0,00} \\
\hline
13-4 & \textbf{40.211,33} & 40.994,70 & 3.691,80 & \textbf{2.805,36} & \textbf{30.544,00} & 31.133,00 & \textbf{43.931,00} & \textbf{43.931,00} & \textbf{0,00} & \textbf{0,00} \\
\hline
14-0 & \textbf{45.978,50} & 46.202,13 & \textbf{3.554,42} & 3.568,23 & 38.071,00 & \textbf{36.932,00} & \textbf{52.940,00} & 53.050,00 & \textbf{0,00} & \textbf{0,00} \\
\hline
14-1 & 53.192,47 & \textbf{52.311,13} & \textbf{3.132,22} & 3.804,77 & 44.905,00 & \textbf{43.816,00} & \textbf{57.918,00} & 58.442,00 & \textbf{0,00} & \textbf{0,00} \\
\hline
14-2 & 49.055,00 & \textbf{48.081,83} & 3.721,61 & \textbf{3.120,08} & 41.976,00 & \textbf{41.310,00} & 54.541,00 & \textbf{53.250,00} & \textbf{0,00} & \textbf{0,00} \\
\hline
14-3 & 48.839,07 & \textbf{48.039,63} & \textbf{2.918,64} & 3.308,78 & 44.045,00 & \textbf{41.717,00} & \textbf{54.227,00} & 54.314,00 & \textbf{0,00} & \textbf{0,00} \\
\hline
14-4 & 51.061,63 & \textbf{50.202,67} & \textbf{3.652,06} & 3.816,22 & \textbf{40.409,00} & 43.666,00 & 57.734,00 & \textbf{57.162,00} & \textbf{0,00} & \textbf{0,00} \\
\hline
50-0 & 61.523,90 & \textbf{42.049,90} & 6.711,40 & \textbf{1.691,20} & 52.905,00 & \textbf{38.028,00} & 79.422,00 & \textbf{45.199,00} & 223,53 & \textbf{38,27} \\
\hline
50-1 & 63.213,00 & \textbf{43.746,23} & 5.465,67 & \textbf{2.057,01} & 49.951,00 & \textbf{38.932,00} & 77.566,00 & \textbf{48.072,00} & 225,87 & \textbf{38,20} \\
\hline
50-2 & 64.692,47 & \textbf{43.919,40} & 5.189,93 & \textbf{1.702,71} & 56.604,00 & \textbf{41.173,00} & 78.037,00 & \textbf{47.435,00} & 224,50 & \textbf{38,03} \\
\hline
50-3 & 58.144,77 & \textbf{40.531,03} & 5.188,43 & \textbf{1.744,95} & 45.609,00 & \textbf{37.277,00} & 69.919,00 & \textbf{43.485,00} & 224,87 & \textbf{38,27} \\
\hline
50-4 & 65.042,13 & \textbf{47.337,60} & 5.341,32 & \textbf{1.875,34} & 55.076,00 & \textbf{43.827,00} & 78.688,00 & \textbf{52.075,00} & 225,77 & \textbf{38,53} \\
\hline
75-0 & 95.186,80 & \textbf{60.065,43} & 7.573,00 & \textbf{1.449,45} & 81.653,00 & \textbf{54.674,00} & 118.561,00 & \textbf{63.188,00} & 312,83 & \textbf{85,70} \\
\hline
75-1 & 91.305,77 & \textbf{57.551,73} & 7.369,88 & \textbf{1.980,91} & 75.680,00 & \textbf{53.679,00} & 104.629,00 & \textbf{62.371,00} & 311,63 & \textbf{85,50} \\
\hline
75-2 & 96.433,67 & \textbf{58.906,93} & 6.155,89 & \textbf{3.169,14} & 82.820,00 & \textbf{49.989,00} & 109.908,00 & \textbf{64.021,00} & 312,37 & \textbf{86,00} \\
\hline
75-3 & 92.104,37 & \textbf{54.406,27} & 8.512,54 & \textbf{3.655,44} & 78.280,00 & \textbf{47.796,00} & 109.581,00 & \textbf{61.561,00} & 312,60 & \textbf{85,07} \\
\hline
75-4 & 95.796,57 & \textbf{59.340,47} & 6.462,50 & \textbf{2.759,21} & 79.952,00 & \textbf{54.673,00} & 109.544,00 & \textbf{66.076,00} & 311,90 & \textbf{85,70} \\
\hline
100-0 & 123.195,40 & \textbf{71.885,23} & 10.459,29 & \textbf{3.790,07} & 104.240,00 & \textbf{69.333,00} & 141.843,00 & \textbf{80.772,00} & 406,93 & \textbf{176,80} \\
\hline
100-1 & 130.871,50 & \textbf{76.400,67} & 8.406,53 & \textbf{3.018,39} & 117.475,00 & \textbf{71.913,00} & 149.618,00 & \textbf{85.389,00} & 413,47 & \textbf{175,13} \\
\hline
100-2 & 128.835,50 & \textbf{72.033,00} & 8.604,97 & \textbf{3.260,31} & 114.894,00 & \textbf{66.123,00} & 148.618,00 & \textbf{77.136,00} & 414,30 & \textbf{176,40} \\
\hline
100-3 & 132.947,30 & \textbf{73.613,17} & 7.705,20 & \textbf{2.168,03} & 119.049,00 & \textbf{68.195,00} & 151.987,00 & \textbf{80.522,00} & 411,83 & \textbf{176,57} \\
\hline
100-4 & 128.267,40 & \textbf{69.673,67} & 8.872,57 & \textbf{4.699,95} & 101.983,00 & \textbf{60.833,00} & 146.894,00 & \textbf{77.334,00} & 412,40 & \textbf{176,60} \\
\hline
\end{tabular}

/tmp/ipykernel_32108/960364897.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_algorithm['filename'] = df_algorithm['filename'].str.replace(r'data/FIS(\d+-\d+)\.txt', r'\1', regex=True)
/tmp/ipykernel_32108/960364897.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_algorithm['filename'] = df_algorithm['filename'].str.replace(r'data/FIS(\d+-\d+)\.txt', r'\1', regex=True)

In [15]:
df_result.to_csv('analysis_mean_min_max_std.csv', index=False)

### Best algorithm per mean

In [16]:
# Find the lowest mean for each filename
min_means = df.groupby('filename')['mean'].min()

# Initialize a dictionary to store counts of best algorithms
best_algorithm_counts = {}

# Iterate over each filename and its corresponding minimum mean
for filename, min_mean in min_means.items():
    # Find all algorithms that achieved the minimum mean for this filename
    best_algorithms_for_file = df[(df['filename'] == filename) & (df['mean'] == min_mean)]['algorithm'].tolist()
    
    # Update the counts in the dictionary
    for algorithm in best_algorithms_for_file:
        best_algorithm_counts[algorithm] = best_algorithm_counts.get(algorithm, 0) + 1

# Calculate the percentage for Memetic
memetic_percentage = best_algorithm_counts.get('Memetic', 0) * 100 / len(df['filename'].unique())
print(f'Memetic showed better results in {memetic_percentage}% of the instances')

# Print the counts of each algorithm
for algorithm, count in best_algorithm_counts.items():
    print(f"{algorithm}: {count}")

Memetic showed better results in 36.92307692307692% of the instances
NearestNeighborhood: 14
CheapestInsertion: 35
Memetic: 24
GeneticImproved: 10

## Melhor solução

In [17]:
def is_smaller_instance(filename):
    # Extrai o número da instância do nome do arquivo
    num = int(filename.split('/')[-1].split('-')[0].replace('FIS', ''))
    return num <= 14

In [18]:
def calculate_results(df):
    # Agrupar por filename e execution
    grouped = df.groupby(['filename', 'execution'])
    results = {}

    # Para cada instância, determinar qual algoritmo teve o menor custo
    for name, group in grouped:
        min_cost = group['cost'].min()
        algorithms_with_min_cost = group[group['cost'] == min_cost]['algorithm'].tolist()

        for algo in df['algorithm'].unique():
            if algo not in results:
                results[algo] = {'win': 0, 'tie': 0, 'lose': 0}

            if algo in algorithms_with_min_cost:
                if len(algorithms_with_min_cost) == 1:
                    results[algo]['win'] += 1
                else:
                    results[algo]['tie'] += 1
            else:
                results[algo]['lose'] += 1

    # Calcular as porcentagens e exibir os resultados
    total_instances = df['filename'].nunique() * df['execution'].nunique()

    for algo, counts in results.items():
        win_percentage = (counts['win'] / total_instances) * 100
        tie_percentage = (counts['tie'] / total_instances) * 100
        lose_percentage = (counts['lose'] / total_instances) * 100
        print(f"Algoritmo {algo} foi melhor em {win_percentage:.2f}% das instâncias, empatou em {tie_percentage:.2f}% e perdeu em {lose_percentage:.2f}%")

In [19]:
df_experiments = pd.read_csv('2023-08-20.csv', delimiter=';')

# Calcular resultados para instâncias menores
print("Resultados para instâncias menores:")
calculate_results(df_experiments[df_experiments['filename'].apply(is_smaller_instance)])

# Calcular resultados para instâncias maiores
print("\nResultados para instâncias maiores:")
calculate_results(df_experiments[~df_experiments['filename'].apply(is_smaller_instance)])

print("\nResultados para instâncias maiores sem o memetic:")
calculate_results(df_experiments[(~df_experiments['filename'].apply(is_smaller_instance)) & (df_experiments['algorithm'] != 'Memetic')])

Resultados para instâncias menores:
Algoritmo Memetic foi melhor em 4.53% das instâncias, empatou em 24.13% e perdeu em 71.33%
Algoritmo GeneticImproved foi melhor em 3.80% das instâncias, empatou em 24.20% e perdeu em 72.00%
Algoritmo NearestNeighborhood foi melhor em 19.93% das instâncias, empatou em 6.33% e perdeu em 73.73%
Algoritmo CheapestInsertion foi melhor em 42.07% das instâncias, empatou em 24.27% e perdeu em 33.67%

Resultados para instâncias maiores:
Algoritmo Memetic foi melhor em 100.00% das instâncias, empatou em 0.00% e perdeu em 0.00%
Algoritmo GeneticImproved foi melhor em 0.00% das instâncias, empatou em 0.00% e perdeu em 100.00%
Algoritmo NearestNeighborhood foi melhor em 0.00% das instâncias, empatou em 0.00% e perdeu em 100.00%
Algoritmo CheapestInsertion foi melhor em 0.00% das instâncias, empatou em 0.00% e perdeu em 100.00%

Resultados para instâncias maiores sem o memetic:
Algoritmo GeneticImproved foi melhor em 23.56% das instâncias, empatou em 0.00% e perdeu em 76.44%
Algoritmo NearestNeighborhood foi melhor em 18.00% das instâncias, empatou em 0.00% e perdeu em 82.00%
Algoritmo CheapestInsertion foi melhor em 58.44% das instâncias, empatou em 0.00% e perdeu em 41.56%